---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```ruby\ndef cumprimentar(nome)\n  \"Olá \" + nome            \nend\n```\n"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```javascript\nfunction cumprimentar(nome) {\n  return \"Olá \" + nome;
    \   \n}\n```\n"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```python\ndef cumprimentar(nome):\n  return \"Olá \" + nome     \n```\n"
  checked: true
name: O computador poliglota
