---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "```ruby\ndef cumprimentar(nome)\n  \"Olá \" + nome              \nend\n```\n"
  checked: false
- value: "```javascript\nfunction cumprimentar(nome) {\n  return \"Olá \" + nome;
    \   \n}\n```\n"
  checked: false
- value: "```python\ndef cumprimentar(nome):\n  return \"Olá \" + nome       \n```\n"
  checked: true
name: O computador poliglota
