---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```ruby def cumprimentar(nome)   \"Olá \" + nome       \t  end ```"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '```javascript function cumprimentar(nome) {   return "Olá " + nome;     }
    ```'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```python def cumprimentar(nome):   return \"Olá \" + nome\t  ```"
  checked: true
name: O computador poliglota
