---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```python\ndef dobro(número):\n  return número * 2     \n```\n"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: |
    ```python
    def dobro(numero):
      return numero + numero
    ```
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```python\ndef dobro(numero):\n  return numero * 2     \n```\n"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```python\ndef dobro(numero)\n  return numero * 2     \n```\n"
  checked: false
name: Não entendo nada
