---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```pythondef dobro(número):   return número * 2```"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```python def dobro(numero):   return numero + numero ```"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```python def dobro(numero):   return numero * 2\t  ```"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```python def dobro(numero)   return numero * 2\t  ```"
  checked: false
name: Não entendo nada
