---
locale: pt
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Resolver uma discussão.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Determinar se um quadro é belo.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Simpatizar com outras pessoas.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Nenhuma das anteriores.
  checked: true
name: Nem tudo está programado
