---
locale: pt
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Resolver uma discussão.
  checked: false
- value: Determinar se um quadro é belo.
  checked: false
- value: Simpatizar com outras pessoas.
  checked: false
- value: Nenhuma das anteriores.
  checked: true
name: Nem tudo está programado
