---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "[Bloco de notas](https://pt.wikipedia.org/wiki/Bloco_de_Notas)"
  checked: false
- value: "[Receita Federal](https://www.gov.br/receitafederal/pt-br)"
  checked: true
- value: "[Instagram](https://www.instagram.com)"
  checked: true
- value: "[Mercado Livre](https://www.mercadolivre.com.br/)"
  checked: true
- value: "[Decolar](https://www.decolar.com/)"
  checked: true
- value: "[Campo Minado](https://pt.wikipedia.org/wiki/Campo_minado)"
  checked: false
- value: "[Fortnite](https://www.epicgames.com/fortnite/pt-BR/home?lang=pt-BR)"
  checked: true
- value: "[Minecraft](https://www.minecraft.net/pt-br)"
  checked: true
- value: "[Paciência](https://pt.wikipedia.org/wiki/Paci%C3%AAncia_(jogo))"
  checked: false
- value: "[Mumuki](https://mumuki.io/home)"
  checked: true
name: Aplicativos vs. Sistemas
