---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: A contabilidade de uma empresa.
  checked: true
- value: O agendamento de um horário.
  checked: true
- value: Corrigir uma prova.
  checked: true
- value: A criação de um videogame.
  checked: true
- value: Realizar videochamadas.
  checked: true
- value: Reconhecer imagens.
  checked: true
- value: Dirigir um robô em Marte.
  checked: true
name: Vamos programando
