---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: A contabilidade de uma empresa.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O agendamento de um horário.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Corrigir uma prova.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: A criação de um videogame.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Realizar videochamadas.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Reconhecer imagens.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Dirigir um robô em Marte.
  checked: true
name: Vamos programando
