---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Liquidificador antigo.
  checked: false
- value: Console de videogames.
  checked: true
- value: Navegador GPS.
  checked: true
- value: Telefone celular.
  checked: true
- value: Uma mesa de madeira.
  checked: false
- value: Caixa eletrônico.
  checked: true
name: Isso também é um computador?
