---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Liquidificador antigo.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Console de videogames.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Navegador GPS.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Telefone celular.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Uma mesa de madeira.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Caixa eletrônico.
  checked: true
name: Isso também é um computador?
