---
locale: pt
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Uma receita culinária.
  checked: false
- value: As instruções para fazer um origami.
  checked: false
- value: Os passos para resolver um cubo Rubik.
  checked: false
- value: A lógica das redes sociais para sugestão de contatos.
  checked: false
- value: Todas as anteriores.
  checked: true
name: Algo com ritmo
