---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Uma receita culinária.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: As instruções para fazer um origami.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Os passos para resolver um cubo Rubik.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: A lógica das redes sociais para sugestão de contatos.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Todas as anteriores.
  checked: true
name: Algo com ritmo
