---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: olá q ta fzndo?
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: olá, o que você está fazendo?
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: olá o que você está fazendo¿
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: olá, o que? está fazendo
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: oál, ¿qeu etsá fanzedno?
  checked: false
name: O que você acha?
