---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: olá q ta fzndo?
  checked: false
- value: olá, o que você está fazendo?
  checked: true
- value: olá o que você está fazendo¿
  checked: false
- value: olá, o que? está fazendo
  checked: false
- value: oál, ¿qeu etsá fanzedno?
  checked: false
name: O que você acha?
